name: burgantevo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  dio: ^5.7.0
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  http: ^1.2.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
 
flutter:
  uses-material-design: true
  assets:
    - assets/images/
